export const packages = [
  {
    id: 1,
    badge: 'Plano 1',
    name: 'Essencial',
    detail: '1 Consulta + 1 Retorno',
    price: 'R$ 600',
    cents: ',00',
    featured: false,
    items: [
      '1 Consulta completa',
      '1 Retorno de acompanhamento',
      'Plano personalizado',
      'Suporte via WhatsApp',
    ],
    waLink: 'https://wa.me/55083999999999?text=Olá%20Dr.%20Paulo!%20Tenho%20interesse%20no%20Plano%201',
  },
  {
    id: 2,
    badge: 'Plano 2 · Mais escolhido',
    name: 'Evolução',
    detail: '2 Consultas + 2 Retornos',
    price: 'R$ 900',
    cents: ',00',
    featured: true,
    items: [
      '2 Consultas completas',
      '2 Retornos de acompanhamento',
      'Plano personalizado e ajustado',
      'Suporte via WhatsApp',
    ],
    waLink: 'https://wa.me/55083999999999?text=Olá%20Dr.%20Paulo!%20Tenho%20interesse%20no%20Plano%202',
  },
  {
    id: 3,
    badge: 'Plano 3',
    name: 'Transformação',
    detail: '3 Consultas + 3 Retornos',
    price: 'R$ 1.300',
    cents: ',00',
    featured: false,
    items: [
      '3 Consultas completas',
      '3 Retornos de acompanhamento',
      'Plano com revisões e otimizações',
      'Suporte via WhatsApp prioritário',
    ],
    waLink: 'https://wa.me/55083999999999?text=Olá%20Dr.%20Paulo!%20Tenho%20interesse%20no%20Plano%203',
  },
]
